
export const companies = [
    {
      id: 1,
      name: "ABC Company",
      contactPerson: "Sushil Chaudhary",
      email: "sushilchaudhary0408@gmail.com",
      phone: "+977 9824281352",
      vmUsed: "12/22",
      registrationStatus: "Approved",
      status: "Active",
      paymentStatus: "Paid",
      vmRequested: "10",
      vmCreated: "5",
      remainingVm: "7",
      cpu: "4 CPUs",
      ram: "8 GB",
      storage: "1TB",
    },
    {
      id: 2,
      name: "XYZ Company",
      contactPerson: "Rahul Chaudhary",
      email: "rahulchaudhary0408@gmail",
      phone: "+977 98273347467",
      vmUsed: "10/22",
      registrationStatus: "Not Approved",
      status: "Unactive",
      paymentStatus: "Due",
      vmRequested: "10",
      vmCreated: "5",
      remainingVm: "7",
      cpu: "4 CPUs",
      ram: "8 GB",
      storage: "1TB",
    },
    {
      id: 3,
      name: "MNO Company",
      contactPerson: "Nishant Chaudhary",
      email: "nishantchaudhary0408@gmail",
      phone: "+977 98674653783",
      vmUsed: "01/22",
      registrationStatus: "Approved",
      status: "Active",
      paymentStatus: "Overdue",
      vmRequested: "10",
      vmCreated: "5",
      remainingVm: "7",
      cpu: "4 CPUs",
      ram: "8 GB",
      storage: "1TB",
    },
    {
      id: 4,
      name: "ABC Company",
      contactPerson: "Sushil Chaudhary",
      email: "sushilchaudhary0408@gmail.com",
      phone: "+977 9824281352",
      vmUsed: "12/22",
      registrationStatus: "Approved",
      status: "Active",
      paymentStatus: "Paid",
      vmRequested: "10",
      vmCreated: "5",
      remainingVm: "7",
      cpu: "4 CPUs",
      ram: "8 GB",
      storage: "1TB",
    },
    {
      id: 5,
      name: "XYZ Company",
      contactPerson: "Rahul Chaudhary",
      email: "rahulchaudhary0408@gmail",
      phone: "+977 98273347467",
      vmUsed: "10/22",
      registrationStatus: "Not Approved",
      status: "Unactive",
      paymentStatus: "Due",
      vmRequested: "10",
      vmCreated: "5",
      remainingVm: "7",
      cpu: "4 CPUs",
      ram: "8 GB",
      storage: "1TB",
    },
    {
      id: 6,
      name: "MNO Company",
      contactPerson: "Nishant Chaudhary",
      email: "nishantchaudhary0408@gmail",
      phone: "+977 98674653783",
      vmUsed: "01/22",
      registrationStatus: "Approved",
      status: "Active",
      paymentStatus: "Overdue",
      vmRequested: "10",
      vmCreated: "5",
      remainingVm: "7",
      cpu: "4 CPUs",
      ram: "8 GB",
      storage: "1TB",
    },
  ];